<?php

define('KENT_STATE_VIEWS_PATH', drupal_get_path('module', 'kent_state_views'));

/**
 * Implements hook_views_plugins().
 */
function kent_state_views_preprocess_page(&$vars) {
    drupal_add_css('//cdnjs.cloudflare.com/ajax/libs/font-awesome/4.2.0/css/font-awesome.css', array('type'=>'external'));
}

/**
 * Implements hook_views_plugins().
 */
function kent_state_views_preprocess_views_view(&$vars) {
    drupal_add_css('//cdnjs.cloudflare.com/ajax/libs/font-awesome/4.2.0/css/font-awesome.css', array('type'=>'external'));
}

function kent_state_views_views_pre_view(&$view, &$display_id, &$args) {
    if($view->name === 'articles'){
        if($view->current_display === 'group_similar_pane'){
            //realign taxonomy args so that there is only one argument
            if(isset($args[1])){
                $boom = explode(',', $args[1]);
                $args[1] = $boom[0];
            }
        }
    }
}

/**
 * Implements hook_theme_registry_alter().
 */
function kent_state_views_theme_registry_alter(&$theme_registry) {
    // Defined path to current module.
    $module_path = drupal_get_path('module', 'kent_state_views');
    // Find all .tpl.php files in this module's folder recursively.
    $template_file_objects = drupal_find_theme_templates($theme_registry, '.tpl.php', $module_path);
    // Itterate through all found template file objects.
    foreach ($template_file_objects as $key => $template_file_object) {
        // If the entry doesnt exist, add it.
        if(!isset($theme_registry[$key])){
            $theme_registry[$key] = $template_file_object;
            $theme_registry[$key]['theme path'] = $module_path;
            $theme_registry[$key]['type'] = 'theme_engine';
        }
        else if (!preg_match('#/themes/#', $theme_registry[$key]['theme path'])) { 
            // If the template has not already been overridden by a theme.
            // Alter the theme path and template elements.
            $theme_registry[$key]['theme path'] = $module_path;
            $theme_registry[$key] = array_merge($theme_registry[$key], $template_file_object);
        }
    }
}

