<?php
/**
 * @file
 * kent_state_core.features.filter.inc
 */

/**
 * Implements hook_filter_default_formats().
 */
function kent_state_core_filter_default_formats() {
  $formats = array();

  // Exported format: Filtered HTML.
  $formats['filtered_html'] = array(
    'format' => 'filtered_html',
    'name' => 'Filtered HTML',
    'cache' => 1,
    'status' => 1,
    'weight' => 0,
    'filters' => array(
      'filter_url' => array(
        'weight' => 0,
        'status' => 1,
        'settings' => array(
          'filter_url_length' => 72,
        ),
      ),
      'htmLawed' => array(
        'weight' => 0,
        'status' => 1,
        'settings' => array(
          'htmLawed' => array(
            'config' => '\'safe\'=>1, \'elements\'=>\'h1, h2, h3, h4, h5, h6, a, p, b, i, pre, mark, div, ul, ol, li, em, strong, cite, code, ol, ul, li, dl, dt, dd, dfn, table, thead, tbody, tfoot, th, tr, td, img\'',
            'spec' => '',
            'help' => 'Tags allowed: \'h1, h2, h3, h4, h5, h6, a, p, b, i, pre, mark, div, ul, ol, li, em, strong, cite, code, ol, ul, li, dl, dt, dd, dfn, table, thead, tbody, tfoot, th, tr, td, img',
          ),
        ),
      ),
      'filter_autop' => array(
        'weight' => 2,
        'status' => 1,
        'settings' => array(),
      ),
      'filter_htmlcorrector' => array(
        'weight' => 10,
        'status' => 1,
        'settings' => array(),
      ),
    ),
  );

  // Exported format: Full HTML.
  $formats['full_html'] = array(
    'format' => 'full_html',
    'name' => 'Full HTML',
    'cache' => 1,
    'status' => 1,
    'weight' => 1,
    'filters' => array(
      'filter_url' => array(
        'weight' => 0,
        'status' => 1,
        'settings' => array(
          'filter_url_length' => 72,
        ),
      ),
      'filter_autop' => array(
        'weight' => 1,
        'status' => 1,
        'settings' => array(),
      ),
      'filter_htmlcorrector' => array(
        'weight' => 10,
        'status' => 1,
        'settings' => array(),
      ),
    ),
  );

  // Exported format: Plain text.
  $formats['plain_text'] = array(
    'format' => 'plain_text',
    'name' => 'Plain text',
    'cache' => 1,
    'status' => 1,
    'weight' => 10,
    'filters' => array(
      'filter_html_escape' => array(
        'weight' => 0,
        'status' => 1,
        'settings' => array(),
      ),
      'filter_url' => array(
        'weight' => 1,
        'status' => 1,
        'settings' => array(
          'filter_url_length' => 72,
        ),
      ),
      'filter_autop' => array(
        'weight' => 2,
        'status' => 1,
        'settings' => array(),
      ),
    ),
  );

  return $formats;
}
