<?php

function kent_state_utilities_node_save(){
    
}

function kent_state_utilities_form_profile_node_form_alter(&$form, &$form_state, $form_id) {
    global $user;
    
    //if we're on the add form, check the current user for previous profiles, clear out the author field if any profile exists
    if($form['nid']['#value'] === NULL){
        $result = db_query('SELECT n.nid FROM {node} n WHERE n.uid = :uid AND n.type = :type', 
                           array(':uid' => $user->uid, ':type'=>'profile')
                           );
        if($result->rowCount() === 1){
            drupal_set_message('<b>Existing profile found for your user, author field has been set to blank on this form.</b>', 'warning');
            $form['author']['name']['#default_value'] = '';
        }
    }
}

function kent_state_utilities_node_validate($node, $form, &$form_state){
    if($node->type === 'profile'){
        //check for existing profiles bound to this user
        if(!empty($form['author']['name']['#value'])){
            $user = user_load_by_name($form['author']['name']['#value']);
            $result = db_query('SELECT n.nid FROM {node} n WHERE n.uid = :uid AND n.type = :type', 
                               array(':uid' => $user->uid, ':type'=>'profile')
                               );
            if($node->nid === NULL){
                if($result->rowCount() === 1){
                    form_set_error('author', t('A user account may only have one profile. Set the author to blank to make an unconnected Profile'));
                }
            }
            else{
                foreach($result as $row){
                    if($row->nid !== $node->nid){
                        form_set_error('author', t('This user already has a profile, please edit the existing one at node/'.$row->nid));
                    }
                }
            }
        }
    }
}

function kent_state_utilities_node_submit($node, $form, &$form_state) {
}
