<?php

define('KENT_STATE_FORMS_PATH', drupal_get_path('module', 'kent_state_forms'));

//$form = drupal_get_form('kent_state_forms_contact');

function kent_state_forms_contact($form, &$form_state) {
    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => t('Submit'),
    );
    return $form;
}
function kent_state_forms_contact_validate($form, &$form_state) {
    // Validation logic.
}
function kent_state_forms_contact_submit($form, &$form_state) {
    // Submission logic.
}
