
<?php

// Convenience function for returning the current module path in the filesystem
function _markdown_monospace_dir($url=true){
    $path = __DIR__;
    if($url){
        $path = ltrim(str_replace(getcwd(), '', __DIR__), '/');
    }
    return $path;
}

/**
 * Implementation of hook_element_info_alter().
 *
 * Loads pre render callback, adds our js and css snippets.
 */
function markdown_monospace_element_info_alter(&$types) {
    ;
    $types['text_format']['#pre_render'][] = 'markdown_monospace_pre_render_text_format';
    drupal_add_js(_markdown_monospace_dir().'/markdown_monospace.js', array('type' => 'file', 'scope' => 'footer'));    
    drupal_add_css('.markdown-active{font-family:monospace;}', array('type'=>'inline'));
}

/**
 * pre render callback
 *
 * Add each textarea and some extra info to Drupal.settings.markdown
 */
function markdown_monospace_pre_render_text_format($element) {
    if(isset($element['format'])){
        //figure out which select box values we need to listen on for triggering our js
        $select_values = array();        
        foreach(filter_formats() as $format){
            $def = filter_list_format($format->format);
            if(array_key_exists('filter_markdown', $def)){
                $select_values[] = $format->format;
            }
        }

        $textarea = array(
            'filter_id' => $element['format']['format']['#id'],
            'textarea_id' => $element['value']['#id'],
            'summary_id' => isset($element['summary']) ? $element['summary']['#id'] : '',
        );
        drupal_add_js(array('markdown_monospace' => array('inputs' => array($textarea))), 'setting');
        drupal_add_js(array('markdown_monospace' => array('select_values' => $select_values)), 'setting');
    }
    return $element;
}
